#pragma once

#include <filesystem>
#include <string>

std::filesystem::path get_repo_root();
std::filesystem::path get_large_data_root();
std::filesystem::path get_whisper_cpp_root();
std::filesystem::path get_whisper_model_path();
std::filesystem::path get_whisper_cli_path_override();
bool is_whisper_gpu_requested();
int get_whisper_gpu_device();
bool is_whisper_flash_attn_enabled();
int get_whisper_threads();
std::filesystem::path get_llama_cpp_root();
std::filesystem::path get_llama_model_path();
bool is_pipeline_debug_enabled();
bool is_correction_enabled();
double get_correction_temperature();
int get_correction_top_k();
double get_correction_top_p();
double get_correction_min_p();
int get_correction_max_output_tokens();
int get_correction_segment_max_chars();
int get_correction_segment_overlap_chars();
int get_correction_force_segmentation_threshold_chars();
std::string get_correction_mode();
std::string get_correction_backend_mode();
bool is_correction_resident_enabled();
std::string get_correction_resident_host();
int get_correction_resident_port();
int get_correction_resident_ctx_size();
int get_correction_resident_gpu_layers();
int get_correction_resident_threads();
int get_correction_resident_startup_timeout_ms();
int get_correction_resident_request_timeout_ms();
int get_correction_resident_total_budget_ms();
int get_correction_resident_per_attempt_timeout_ms();
bool is_streaming_enabled();
int get_stream_step_ms();
int get_stream_length_ms();
int get_stream_keep_ms();
bool is_stream_finalize_on_release_enabled();
std::string describe_paths_json();
